---

- hosts: "maxscale"
  become: true
  become_user: root
  vars_files:
    - '../inventory/group_vars/{{ ansible_os_family|lower }}.yml'

  tasks:
  - name: "Installing New MariaDB Repo"
    shell: curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash -s -- --mariadb-server-version=mariadb-{{ mariadb_version }} --mariadb-maxscale-version={{ maxscale_version }}
    args:
      warn: false

  - name: "Installing Some Basic Packages"
    package:
      name: '{{ packages }}'
      state: present
    vars:
      packages:
      - '{{ git }}'
      - '{{ mariadb_client }}'
      - '{{ mysql_python }}'
      - '{{ nano }}'

  - name: "Installing MaxScale & Sysbench"
    package:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - maxscale
      - sysbench

  - name: "Removing Old Secrets If Necessary"
    file:
      path: /var/lib/maxscale/.secrets
      state: absent

  - name: "Creating New Secrets"
    command: maxkeys /var/lib/maxscale/

  - name: "Changing Owner Of Secrets"
    file:
      path: /var/lib/maxscale/.secrets
      state: touch
      owner: maxscale
      group: maxscale

  - name: "Creating Encrypted Password"
    command: maxpasswd /var/lib/maxscale/ {{ maxscale_pass }}
    register: hexadecimal

  - name: "Copying maxscale.cnf"
    template:
      src: ../templates/maxscale.j2
      dest: /etc/maxscale.cnf

  - name: "Creating MaxScale Extra Folder"
    file:
      path: /etc/maxscale.cnf.d/
      state: directory
      owner: maxscale
      group: maxscale

  - name: "Restarting MaxScale"
    systemd:
      name: maxscale
      enabled: true
      state: restarted
