---

boost: libboost-all-dev
cmake: cmake
development_tools: build-essential
expect: expect
file: file
git: git
jemalloc: libjemalloc1
libaio: libaio1
lz4_devel: libroslz4-dev
lz4: liblz4-tool
mariadb_backup: mariadb-backup
mariadb_client: mariadb-client
mariadb_libs: mariadb-libs
mariadb_server: mariadb-server
mariadb: mariadb*
maxscale_cdc_connector: maxscale-cdc-connector
mlocate: mlocate
mysql_python: python-mysqldb
nano: nano
net_tools: net-tools
nmap: nmap
numactl_libs: libnuma1
openssl: openssl
percona: percona-xtradb-cluster-server-5.7
perl_DBI: libdbi-perl
perl: perl
pid: /var/run/mysqld/mysqld.pid
pigz: pigz
readline_dev: libreadline-dev
rsync: rsync
snappy: libsnappy1v5
socat: socat
socket: /var/run/mysqld/mysqld.sock
tcl: libtcl8.6
tcp_wrappers_devel: libwrap0-dev
tzdata: tzdata
unzip: unzip
version: bionic
xtrabackup: percona-xtrabackup
zlib: zlibc
